### ISSUE TITLE
Missing items when merging PublishSubject

### ISSUE THREAD

**Issue by Luegg** [monifu/monifu#50]
I've recently came across some strange behavior that may be a bug:

When merging a publish subject, the items emitted immediately after the subscription are never sent to the observer. Hence, the following dumps nothing to the console:

```scala
val i = PublishSubject[Int]()

val merged = Observable.merge(i)

merged.dump("merged").foreach(_ => ())

i.onNext(1)
```

`i.onNext(1)` immediately yields `Continue` as if there where no subscriptions. When subscribing directly to `i` everything works as expected. Also, rescheduling the `onNext` call works:

```scala
val i = PublishSubject[Int]()

val merged = Observable.merge(i)

merged.dump("merged").foreach(_ => ())

implicitly[Scheduler].execute {
  i.onNext(1)
}
```

I use monifu only with ScalaJS so I didn't check if this also applies when running in the JVM.

**Comment by alexandru** [comment]
@Luegg, sorry for the late reply, something has been wrong with my email and I just noticed the issue. Don't worry as this isn't a bug. The explanation is this:

1. `PublishSubject` tries to push `onNext` events synchronously and it works synchronously if the subscribers are synchronous
2. your subscriber is obviously not synchronous, but here's the thing ... `Observable.merge` is the same as `Observable.fromIterable(observables).merge` and it executes asynchronously
3. this means that the subscription related to your `merged.foreach(() => ())` is executed *after* `i.onNext`

Consequently, this is why scheduling your `onNext` works, because it happens to be scheduled for execution (when running in the browser) after your subscription happens.

See this test: https://github.com/monifu/monifu/blob/master/monifu/shared/src/test/scala/monifu/reactive/subjects/PublishSubjectSuite.scala#L80
